import type { ChartInput, Gender, StarBrightness } from "@/lib/chart";

type FixturePalaceStars = Record<string, string[]>;
type FixturePalaceStates = Record<string, Record<string, string>>;
type FixtureProvenance = "pdf" | "reference-image" | "web-cross-check" | "engine-regression";

export const REQUIRED_GOLDEN_FIXTURE_HOURS = ["Tý", "Dần", "Ngọ", "Hợi"] as const;
export const EXTERNAL_FIXTURE_PROVENANCE = ["pdf", "reference-image", "web-cross-check"] as const;

export type ChartFixture = {
  id: string;
  source: string;
  provenance: FixtureProvenance;
  coverage: {
    hourBranch: string;
    gender: Gender;
    hasTuan: boolean;
    hasTriet: boolean;
    starStates: StarBrightness[];
  };
  input: ChartInput;
  expected: {
    solar: { day: number; month: number; year: number };
    lunar: { day: number; month: number; year: number; leap: boolean };
    canChi: { year: string; month: string; day: string; hour: string };
    menh: string;
    than: string;
    cuc: string;
    banMenh: string;
    menhChu: string;
    thanChu: string;
    laiNhan?: string;
    menhCucRelation: string;
    firstDaiVan: { palace: string; branch: string; range: string };
    boneWeightLabel?: string;
    mainStarsByPalace: FixturePalaceStars;
    supportStarsInclude?: FixturePalaceStars;
    yearlyStarsInclude?: FixturePalaceStars;
    starStatesInclude?: FixturePalaceStates;
  };
};

export const CHART_FIXTURES: ChartFixture[] = [
  {
    id: "aituvi-reference-1995-suu-hour",
    source: "Reference image supplied by user, cross-checked against lasotuvi-style star placement rules",
    provenance: "reference-image",
    coverage: {
      hourBranch: "Sửu",
      gender: "male",
      hasTuan: true,
      hasTriet: true,
      starStates: ["B", "H", "Đ", "V"],
    },
    input: {
      fullName: "Hứa Thị Thúy Hằng",
      gender: "male",
      calendarType: "solar",
      day: 3,
      month: 4,
      year: 1995,
      birthHour: 1,
      viewYear: 2026,
      timezone: "Asia/Bangkok",
    },
    expected: {
      solar: { day: 3, month: 4, year: 1995 },
      lunar: { day: 4, month: 3, year: 1995, leap: false },
      canChi: { year: "Ất Hợi", month: "Canh Thìn", day: "Giáp Tý", hour: "Ất Sửu" },
      menh: "Mão",
      than: "Tỵ",
      cuc: "Thổ ngũ cục",
      banMenh: "Sơn Đầu Hỏa",
      menhChu: "Cự Môn",
      thanChu: "Thiên Cơ",
      laiNhan: "Thiên Di",
      menhCucRelation: "Mệnh Hỏa sinh Cục Thổ",
      firstDaiVan: { palace: "Mệnh", branch: "Mão", range: "5-14" },
      boneWeightLabel: "4 lượng 8 chỉ",
      mainStarsByPalace: {
        "Mệnh": ["Thiên Phủ"],
        "Phụ Mẫu": ["Thái Âm"],
        "Phúc Đức": ["Liêm Trinh", "Tham Lang"],
        "Điền Trạch": ["Cự Môn"],
        "Quan Lộc": ["Thiên Tướng"],
        "Nô Bộc": ["Thiên Đồng", "Thiên Lương"],
        "Thiên Di": ["Vũ Khúc", "Thất Sát"],
        "Tật Ách": ["Thái Dương"],
        "Tài Bạch": ["Vô chính diệu"],
        "Tử Tức": ["Thiên Cơ"],
        "Phu Thê": ["Tử Vi", "Phá Quân"],
        "Huynh Đệ": ["Vô chính diệu"],
      },
      supportStarsInclude: {
        "Mệnh": ["Lộc Tồn", "Bác Sĩ", "Long Trì", "Thiên Quý"],
        "Phụ Mẫu": ["Kình Dương", "Hóa Kỵ (Thái Âm)"],
        "Nô Bộc": ["Tuần", "Thiên Thương", "Hóa Quyền (Thiên Lương)"],
        "Thiên Di": ["Tuần"],
        "Điền Trạch": ["Triệt"],
        "Quan Lộc": ["Triệt"],
        "Tật Ách": ["Thiên Sứ"],
        "Tử Tức": ["Hóa Lộc (Thiên Cơ)"],
        "Phu Thê": ["Hóa Khoa (Tử Vi)"],
      },
      yearlyStarsInclude: {
        "Phụ Mẫu": ["L.Đà La"],
        "Điền Trạch": ["L.Thái Tuế", "L.Kình Dương"],
        "Nô Bộc": ["L.Tang Môn", "L.Thiên Mã"],
        "Huynh Đệ": ["L.Bạch Hổ"],
      },
      starStatesInclude: {
        "Mệnh": { "Thiên Phủ": "B" },
        "Phúc Đức": { "Liêm Trinh": "H", "Tham Lang": "H" },
        "Quan Lộc": { "Thiên Tướng": "Đ" },
        "Phu Thê": { "Tử Vi": "Đ", "Phá Quân": "V" },
      },
    },
  },
  {
    id: "giap-tuat-1994-suu-hour",
    source: "Rule fixture for Giáp Tuất male chart, covers Hỏa cục and forward đại vận",
    provenance: "engine-regression",
    coverage: {
      hourBranch: "Sửu",
      gender: "male",
      hasTuan: true,
      hasTriet: true,
      starStates: [],
    },
    input: {
      fullName: "Kiều Tấn Cường",
      gender: "male",
      calendarType: "solar",
      day: 3,
      month: 4,
      year: 1994,
      birthHour: 1,
      viewYear: 2026,
      timezone: "Asia/Bangkok",
    },
    expected: {
      solar: { day: 3, month: 4, year: 1994 },
      lunar: { day: 23, month: 2, year: 1994, leap: false },
      canChi: { year: "Giáp Tuất", month: "Đinh Mão", day: "Kỷ Mùi", hour: "Ất Sửu" },
      menh: "Dần",
      than: "Thìn",
      cuc: "Hỏa lục cục",
      banMenh: "Sơn Đầu Hỏa",
      menhChu: "Lộc Tồn",
      thanChu: "Thiên Lương",
      menhCucRelation: "Mệnh Hỏa hòa Cục Hỏa",
      firstDaiVan: { palace: "Mệnh", branch: "Dần", range: "6-15" },
      mainStarsByPalace: {
        "Mệnh": ["Tham Lang"],
        "Phụ Mẫu": ["Thiên Cơ", "Cự Môn"],
        "Phúc Đức": ["Tử Vi", "Thiên Tướng"],
        "Điền Trạch": ["Thiên Lương"],
        "Quan Lộc": ["Thất Sát"],
        "Nô Bộc": ["Vô chính diệu"],
        "Thiên Di": ["Liêm Trinh"],
        "Tật Ách": ["Vô chính diệu"],
        "Tài Bạch": ["Phá Quân"],
        "Tử Tức": ["Thiên Đồng"],
        "Phu Thê": ["Vũ Khúc", "Thiên Phủ"],
        "Huynh Đệ": ["Thái Dương", "Thái Âm"],
      },
      supportStarsInclude: {
        "Mệnh": ["Lộc Tồn", "Bác Sĩ"],
        "Nô Bộc": ["Thiên Thương"],
        "Thiên Di": ["Hóa Lộc (Liêm Trinh)", "Tuần", "Triệt"],
        "Tật Ách": ["Thiên Sứ"],
        "Tài Bạch": ["Hóa Quyền (Phá Quân)"],
        "Phu Thê": ["Hóa Khoa (Vũ Khúc)"],
      },
    },
  },
  {
    id: "tracuutuvi-pdf-kieu-tan-cuong-1995-dan-hour",
    source: "Golden fixture extracted from user-provided tracuutuvi PDF La_so_tu_vi_KIEU_TAN_CUONG.pdf",
    provenance: "pdf",
    coverage: {
      hourBranch: "Dần",
      gender: "male",
      hasTuan: true,
      hasTriet: true,
      starStates: ["M", "V", "Đ", "H"],
    },
    input: {
      fullName: "Kiều Tấn Cường",
      gender: "male",
      calendarType: "solar",
      day: 7,
      month: 5,
      year: 1995,
      birthHour: 4,
      birthMinute: 26,
      viewYear: 2026,
      timezone: "Asia/Bangkok",
    },
    expected: {
      solar: { day: 7, month: 5, year: 1995 },
      lunar: { day: 8, month: 4, year: 1995, leap: false },
      canChi: { year: "Ất Hợi", month: "Tân Tỵ", day: "Mậu Tuất", hour: "Giáp Dần" },
      menh: "Mão",
      than: "Mùi",
      cuc: "Thổ ngũ cục",
      banMenh: "Sơn Đầu Hỏa",
      menhChu: "Cự Môn",
      thanChu: "Thiên Cơ",
      menhCucRelation: "Mệnh Hỏa sinh Cục Thổ",
      firstDaiVan: { palace: "Mệnh", branch: "Mão", range: "5-14" },
      boneWeightLabel: "4 lượng 1 chỉ",
      mainStarsByPalace: {
        "Mệnh": ["Thiên Tướng"],
        "Phụ Mẫu": ["Thiên Cơ", "Thiên Lương"],
        "Phúc Đức": ["Tử Vi", "Thất Sát"],
        "Điền Trạch": ["Vô chính diệu"],
        "Quan Lộc": ["Vô chính diệu"],
        "Nô Bộc": ["Vô chính diệu"],
        "Thiên Di": ["Liêm Trinh", "Phá Quân"],
        "Tật Ách": ["Vô chính diệu"],
        "Tài Bạch": ["Thiên Phủ"],
        "Tử Tức": ["Thiên Đồng", "Thái Âm"],
        "Phu Thê": ["Vũ Khúc", "Tham Lang"],
        "Huynh Đệ": ["Thái Dương", "Cự Môn"],
      },
      supportStarsInclude: {
        "Mệnh": ["Lộc Tồn", "Quan Phù", "Bác Sĩ", "Long Trì"],
        "Phụ Mẫu": ["Kình Dương", "Thiên Riêu", "Hóa Lộc (Thiên Cơ)", "Hóa Quyền (Thiên Lương)"],
        "Phúc Đức": ["Thiên Mã", "Thiên Hư", "Hóa Khoa (Tử Vi)"],
        "Điền Trạch": ["Văn Khúc", "Triệt", "Thiên Trù"],
        "Quan Lộc": ["Hỏa Tinh", "Thiên Khốc", "Triệt"],
        "Nô Bộc": ["Văn Xương", "Thiên Thương", "Thiên Việt", "Thiên Phúc", "Tuần"],
        "Thiên Di": ["Địa Không", "Tuần"],
        "Tử Tức": ["Linh Tinh", "Thiên Hình", "Hóa Kỵ (Thái Âm)"],
        "Phu Thê": ["Tang Môn", "Địa Kiếp"],
        "Huynh Đệ": ["Đà La", "Tam Thai", "Ân Quang"],
      },
      yearlyStarsInclude: {
        "Phụ Mẫu": ["L.Đà La"],
        "Phúc Đức": ["L.Lộc Tồn"],
        "Điền Trạch": ["L.Thái Tuế", "L.Kình Dương", "LN Văn tinh"],
        "Nô Bộc": ["L.Tang Môn", "L.Thiên Mã"],
        "Tử Tức": ["L.Thiên Hư", "L.Thiên Khốc"],
        "Huynh Đệ": ["L.Bạch Hổ"],
      },
      starStatesInclude: {
        "Mệnh": { "Thiên Tướng": "H" },
        "Phụ Mẫu": { "Thiên Cơ": "M", "Thiên Lương": "M", "Kình Dương": "Đ", "Thiên Riêu": "H" },
        "Phúc Đức": { "Tử Vi": "M", "Thất Sát": "V", "Thiên Mã": "Đ" },
        "Điền Trạch": { "Văn Khúc": "H" },
        "Quan Lộc": { "Hỏa Tinh": "H" },
        "Thiên Di": { "Liêm Trinh": "H", "Phá Quân": "H", "Địa Không": "H" },
        "Tài Bạch": { "Thiên Phủ": "Đ" },
        "Tử Tức": { "Thiên Đồng": "V", "Thái Âm": "V", "Linh Tinh": "H", "Thiên Hình": "H" },
        "Phu Thê": { "Vũ Khúc": "M", "Tham Lang": "M", "Tang Môn": "H", "Địa Kiếp": "H" },
        "Huynh Đệ": { "Thái Dương": "V", "Cự Môn": "V", "Đà La": "H" },
      },
    },
  },
  {
    id: "lasotuvi-web-nham-than-1992-ty-hour",
    source:
      "Web cross-check against lasotuvi.com generated chart https://lasotuvi.com/?hash=8x2Y_X8rC3llN5RVsl4WDROsvjq0hFst8l1EFUCGWL1ibHNHMFm57sU; locks solar/lunar date, Can Chi, Cuc, Ban Menh, Menh/Than and main-star map",
    provenance: "web-cross-check",
    coverage: {
      hourBranch: "Tý",
      gender: "male",
      hasTuan: true,
      hasTriet: true,
      starStates: ["M", "V", "Đ", "B", "H"],
    },
    input: {
      fullName: "Web Tý sample",
      gender: "male",
      calendarType: "solar",
      day: 15,
      month: 8,
      year: 1992,
      birthHour: 0,
      viewYear: 2026,
      timezone: "Asia/Bangkok",
    },
    expected: {
      solar: { day: 15, month: 8, year: 1992 },
      lunar: { day: 17, month: 7, year: 1992, leap: false },
      canChi: { year: "Nhâm Thân", month: "Mậu Thân", day: "Quý Hợi", hour: "Nhâm Tý" },
      menh: "Thân",
      than: "Thân",
      cuc: "Thổ ngũ cục",
      banMenh: "Kiếm Phong Kim",
      menhChu: "Liêm Trinh",
      thanChu: "Văn Xương",
      laiNhan: "Quan Lộc",
      menhCucRelation: "Cục Thổ sinh Mệnh Kim",
      firstDaiVan: { palace: "Mệnh", branch: "Thân", range: "5-14" },
      boneWeightLabel: "4 lượng 1 chỉ",
      mainStarsByPalace: {
        "Mệnh": ["Thất Sát"],
        "Phụ Mẫu": ["Thiên Đồng"],
        "Phúc Đức": ["Vũ Khúc"],
        "Điền Trạch": ["Thái Dương"],
        "Quan Lộc": ["Phá Quân"],
        "Nô Bộc": ["Thiên Cơ"],
        "Thiên Di": ["Tử Vi", "Thiên Phủ"],
        "Tật Ách": ["Thái Âm"],
        "Tài Bạch": ["Tham Lang"],
        "Tử Tức": ["Cự Môn"],
        "Phu Thê": ["Liêm Trinh", "Thiên Tướng"],
        "Huynh Đệ": ["Thiên Lương"],
      },
      supportStarsInclude: {
        "Phúc Đức": ["Tuần", "Hóa Kỵ (Vũ Khúc)"],
        "Điền Trạch": ["Tuần"],
        "Thiên Di": ["Triệt", "Hóa Quyền (Tử Vi)", "Hóa Khoa (Thiên Phủ)"],
        "Tật Ách": ["Triệt"],
        "Huynh Đệ": ["Hóa Lộc (Thiên Lương)"],
      },
      starStatesInclude: {
        "Mệnh": { "Thất Sát": "M" },
        "Phúc Đức": { "Vũ Khúc": "M", "Đà La": "H", "Linh Tinh": "Đ", "Hóa Kỵ (Vũ Khúc)": "H" },
        "Điền Trạch": { "Thái Dương": "H", "Địa Kiếp": "Đ", "Địa Không": "Đ" },
        "Quan Lộc": { "Phá Quân": "M", "Kình Dương": "H" },
        "Nô Bộc": { "Thiên Cơ": "Đ" },
        "Thiên Di": { "Tử Vi": "V", "Thiên Phủ": "M", "Hỏa Tinh": "Đ", "Thiên Mã": "Đ" },
        "Tật Ách": { "Thái Âm": "H", "Thiên Hình": "H" },
        "Tài Bạch": { "Tham Lang": "M", "Bạch Hổ": "H" },
        "Tử Tức": { "Cự Môn": "H" },
        "Phu Thê": { "Liêm Trinh": "M", "Thiên Tướng": "V" },
        "Huynh Đệ": { "Thiên Lương": "Đ", "Thiên Riêu": "H", "Hóa Lộc (Thiên Lương)": "Đ" },
      },
    },
  },
  {
    id: "lunar-new-year-2026-ty-hour",
    source: "Lunar-input regression fixture, covers lunar to solar conversion and same Menh/Than palace",
    provenance: "engine-regression",
    coverage: {
      hourBranch: "Tý",
      gender: "female",
      hasTuan: true,
      hasTriet: true,
      starStates: [],
    },
    input: {
      fullName: "Lunar sample",
      gender: "female",
      calendarType: "lunar",
      day: 1,
      month: 1,
      year: 2026,
      birthHour: 23,
      viewYear: 2026,
      timezone: "Asia/Bangkok",
    },
    expected: {
      solar: { day: 17, month: 2, year: 2026 },
      lunar: { day: 1, month: 1, year: 2026, leap: false },
      canChi: { year: "Bính Ngọ", month: "Canh Dần", day: "Nhâm Tuất", hour: "Canh Tý" },
      menh: "Dần",
      than: "Dần",
      cuc: "Mộc tam cục",
      banMenh: "Thiên Hà Thủy",
      menhChu: "Phá Quân",
      thanChu: "Hỏa Tinh",
      menhCucRelation: "Mệnh Thủy sinh Cục Mộc",
      firstDaiVan: { palace: "Mệnh", branch: "Dần", range: "3-12" },
      mainStarsByPalace: {
        "Mệnh": ["Tham Lang"],
        "Phụ Mẫu": ["Thiên Cơ", "Cự Môn"],
        "Phúc Đức": ["Tử Vi", "Thiên Tướng"],
        "Điền Trạch": ["Thiên Lương"],
        "Quan Lộc": ["Thất Sát"],
        "Nô Bộc": ["Vô chính diệu"],
        "Thiên Di": ["Liêm Trinh"],
        "Tật Ách": ["Vô chính diệu"],
        "Tài Bạch": ["Phá Quân"],
        "Tử Tức": ["Thiên Đồng"],
        "Phu Thê": ["Vũ Khúc", "Thiên Phủ"],
        "Huynh Đệ": ["Thái Dương", "Thái Âm"],
      },
      supportStarsInclude: {
        "Mệnh": ["Tuần"],
        "Phụ Mẫu": ["Hóa Quyền (Thiên Cơ)", "Tuần"],
        "Nô Bộc": ["Thiên Không", "Thiên Thương"],
        "Tật Ách": ["Thiên Sứ"],
        "Phúc Đức": ["Văn Khúc", "Triệt"],
        "Điền Trạch": ["Lộc Tồn", "Triệt"],
        "Quan Lộc": ["Thái Tuế"],
        "Tài Bạch": ["Văn Xương", "Hóa Khoa (Văn Xương)"],
        "Tử Tức": ["Hóa Lộc (Thiên Đồng)"],
      },
    },
  },
  {
    id: "canh-ngo-1990-female-thin-hour",
    source: "Regression fixture for Canh Ngo female chart, covers solar input, Than at Dau, Lai Nhan Dien Trach, and 2026 yearly stars",
    provenance: "engine-regression",
    coverage: {
      hourBranch: "Thìn",
      gender: "female",
      hasTuan: true,
      hasTriet: true,
      starStates: ["M", "V", "Đ", "H"],
    },
    input: {
      fullName: "Fixture female 1990",
      gender: "female",
      calendarType: "solar",
      day: 19,
      month: 5,
      year: 1990,
      birthHour: 8,
      viewYear: 2026,
      timezone: "Asia/Bangkok",
    },
    expected: {
      solar: { day: 19, month: 5, year: 1990 },
      lunar: { day: 25, month: 4, year: 1990, leap: false },
      canChi: { year: "Canh Ngọ", month: "Tân Tỵ", day: "Giáp Thân", hour: "Mậu Thìn" },
      menh: "Sửu",
      than: "Dậu",
      cuc: "Hỏa lục cục",
      banMenh: "Lộ Bàng Thổ",
      menhChu: "Phá Quân",
      thanChu: "Hỏa Tinh",
      laiNhan: "Điền Trạch",
      menhCucRelation: "Cục Hỏa sinh Mệnh Thổ",
      firstDaiVan: { palace: "Mệnh", branch: "Sửu", range: "6-15" },
      boneWeightLabel: "4 lượng 2 chỉ",
      mainStarsByPalace: {
        "Mệnh": ["Tử Vi", "Phá Quân"],
        "Phụ Mẫu": ["Vô chính diệu"],
        "Phúc Đức": ["Thiên Phủ"],
        "Điền Trạch": ["Thái Âm"],
        "Quan Lộc": ["Liêm Trinh", "Tham Lang"],
        "Nô Bộc": ["Cự Môn"],
        "Thiên Di": ["Thiên Tướng"],
        "Tật Ách": ["Thiên Đồng", "Thiên Lương"],
        "Tài Bạch": ["Vũ Khúc", "Thất Sát"],
        "Tử Tức": ["Thái Dương"],
        "Phu Thê": ["Vô chính diệu"],
        "Huynh Đệ": ["Thiên Cơ"],
      },
      supportStarsInclude: {
        "Mệnh": ["Thiên Việt", "Đường Phù"],
        "Điền Trạch": ["Thiên Riêu", "Hóa Kỵ (Thái Âm)"],
        "Nô Bộc": ["Văn Xương", "Thiên Thương", "Triệt"],
        "Thiên Di": ["Đà La", "Địa Không", "Linh Tinh", "Tả Phù", "Hữu Bật", "Triệt"],
        "Tật Ách": ["Lộc Tồn", "Văn Khúc", "Thiên Mã", "Hóa Khoa (Thiên Đồng)"],
        "Tài Bạch": ["Kình Dương", "Hỏa Tinh", "Hóa Quyền (Vũ Khúc)"],
        "Tử Tức": ["Tuần", "Hóa Lộc (Thái Dương)"],
        "Phu Thê": ["Tuần"],
      },
      yearlyStarsInclude: {
        "Phụ Mẫu": ["L.Bạch Hổ"],
        "Điền Trạch": ["L.Đà La"],
        "Quan Lộc": ["L.Lộc Tồn"],
        "Nô Bộc": ["LN Văn tinh", "L.Thái Tuế", "L.Kình Dương"],
        "Tật Ách": ["L.Tang Môn", "L.Thiên Mã"],
        "Huynh Đệ": ["L.Thiên Hư", "L.Thiên Khốc"],
      },
      starStatesInclude: {
        "Mệnh": { "Tử Vi": "Đ", "Phá Quân": "V" },
        "Điền Trạch": { "Thái Âm": "H", "Thiên Riêu": "H", "Hóa Kỵ (Thái Âm)": "H" },
        "Quan Lộc": { "Liêm Trinh": "H", "Tham Lang": "H" },
        "Thiên Di": { "Thiên Tướng": "Đ", "Đà La": "H", "Địa Không": "H", "Linh Tinh": "Đ" },
        "Tật Ách": { "Thiên Đồng": "M", "Thiên Lương": "M", "Thiên Mã": "Đ", "Hóa Khoa (Thiên Đồng)": "Đ" },
        "Tài Bạch": { "Vũ Khúc": "Đ", "Thất Sát": "H", "Kình Dương": "H", "Hỏa Tinh": "H", "Hóa Quyền (Vũ Khúc)": "Đ" },
        "Tử Tức": { "Thái Dương": "H", "Hóa Lộc (Thái Dương)": "Đ" },
        "Huynh Đệ": { "Thiên Cơ": "Đ", "Thiên Hư": "H", "Thiên Khốc": "Đ", "Thiên Hình": "H" },
      },
    },
  },
  {
    id: "rule-lock-mau-thin-1988-ngo-hour",
    source:
      "Web cross-check against lasotuvi.com generated chart https://lasotuvi.com/?hash=o2UdqaiXh71P9N-gJ7QDfTLrNOpCuVDsJ7lUZIk-7vYO7KpAwmy3YyFG; locks solar/lunar date, Can Chi, Cuc, Ban Menh, Menh/Than and main-star map",
    provenance: "web-cross-check",
    coverage: {
      hourBranch: "Ngọ",
      gender: "male",
      hasTuan: true,
      hasTriet: true,
      starStates: ["M", "V", "Đ", "B", "H"],
    },
    input: {
      fullName: "Golden Ngọ sample",
      gender: "male",
      calendarType: "solar",
      day: 12,
      month: 9,
      year: 1988,
      birthHour: 12,
      viewYear: 2026,
      timezone: "Asia/Bangkok",
    },
    expected: {
      solar: { day: 12, month: 9, year: 1988 },
      lunar: { day: 2, month: 8, year: 1988, leap: false },
      canChi: { year: "Mậu Thìn", month: "Tân Dậu", day: "Canh Ngọ", hour: "Nhâm Ngọ" },
      menh: "Mão",
      than: "Mão",
      cuc: "Thủy nhị cục",
      banMenh: "Đại Lâm Mộc",
      menhChu: "Liêm Trinh",
      thanChu: "Văn Xương",
      laiNhan: "Điền Trạch",
      menhCucRelation: "Cục Thủy sinh Mệnh Mộc",
      firstDaiVan: { palace: "Mệnh", branch: "Mão", range: "2-11" },
      boneWeightLabel: "4 lượng 7 chỉ",
      mainStarsByPalace: {
        "Mệnh": ["Thái Âm"],
        "Phụ Mẫu": ["Tham Lang"],
        "Phúc Đức": ["Cự Môn"],
        "Điền Trạch": ["Liêm Trinh", "Thiên Tướng"],
        "Quan Lộc": ["Thiên Lương"],
        "Nô Bộc": ["Thất Sát"],
        "Thiên Di": ["Thiên Đồng"],
        "Tật Ách": ["Vũ Khúc"],
        "Tài Bạch": ["Thái Dương"],
        "Tử Tức": ["Phá Quân"],
        "Phu Thê": ["Thiên Cơ"],
        "Huynh Đệ": ["Tử Vi", "Thiên Phủ"],
      },
      supportStarsInclude: {
        "Mệnh": ["Hóa Quyền (Thái Âm)", "Hóa Khoa (Hữu Bật)"],
        "Phụ Mẫu": ["Đà La", "Linh Tinh", "Văn Xương", "Hóa Lộc (Tham Lang)"],
        "Phúc Đức": ["Thiên Không", "Địa Kiếp", "Địa Không", "Kiếp Sát"],
        "Điền Trạch": ["Kình Dương"],
        "Nô Bộc": ["Hỏa Tinh", "Văn Tinh"],
        "Tật Ách": ["Văn Khúc", "Tuần"],
        "Tài Bạch": ["Tuần"],
        "Tử Tức": ["Triệt"],
        "Phu Thê": ["Triệt", "Hóa Kỵ (Thiên Cơ)"],
        "Huynh Đệ": ["Thiên Mã"],
      },
      yearlyStarsInclude: {
        "Phụ Mẫu": ["L.Đà La"],
        "Phúc Đức": ["L.Lộc Tồn"],
        "Điền Trạch": ["LN Văn tinh", "L.Thái Tuế", "L.Kình Dương"],
        "Nô Bộc": ["L.Tang Môn", "L.Thiên Mã"],
        "Tử Tức": ["L.Thiên Hư", "L.Thiên Khốc"],
        "Huynh Đệ": ["L.Bạch Hổ"],
      },
      starStatesInclude: {
        "Mệnh": { "Thái Âm": "H", "Hóa Quyền (Thái Âm)": "Đ", "Hóa Khoa (Hữu Bật)": "Đ" },
        "Phụ Mẫu": { "Tham Lang": "M", "Đà La": "H", "Linh Tinh": "Đ" },
        "Phúc Đức": { "Cự Môn": "H", "Địa Kiếp": "Đ", "Địa Không": "Đ" },
        "Điền Trạch": { "Liêm Trinh": "M", "Thiên Tướng": "V", "Kình Dương": "H" },
        "Quan Lộc": { "Thiên Lương": "Đ" },
        "Nô Bộc": { "Thất Sát": "M", "Hỏa Tinh": "H" },
        "Thiên Di": { "Thiên Đồng": "H" },
        "Tật Ách": { "Vũ Khúc": "M" },
        "Tài Bạch": { "Thái Dương": "H" },
        "Tử Tức": { "Phá Quân": "M" },
        "Phu Thê": { "Thiên Cơ": "Đ", "Hóa Kỵ (Thiên Cơ)": "H" },
        "Huynh Đệ": { "Tử Vi": "V", "Thiên Phủ": "M", "Thiên Mã": "Đ" },
      },
    },
  },
  {
    id: "rule-lock-tan-ty-2001-hoi-hour",
    source:
      "Web cross-check against lasotuvi.com generated chart https://lasotuvi.com/?hash=wQltM0OFGSPDllwLLQ6oH4KYIqzl6RMnR-7MGRbEDBUgHR2iHkg9cKczaA; locks solar/lunar date, Can Chi, Cuc, Ban Menh, Menh/Than and main-star map",
    provenance: "web-cross-check",
    coverage: {
      hourBranch: "Hợi",
      gender: "female",
      hasTuan: true,
      hasTriet: true,
      starStates: ["M", "V", "Đ", "B", "H"],
    },
    input: {
      fullName: "Golden Hợi sample",
      gender: "female",
      calendarType: "solar",
      day: 21,
      month: 11,
      year: 2001,
      birthHour: 22,
      viewYear: 2026,
      timezone: "Asia/Bangkok",
    },
    expected: {
      solar: { day: 21, month: 11, year: 2001 },
      lunar: { day: 7, month: 10, year: 2001, leap: false },
      canChi: { year: "Tân Tỵ", month: "Kỷ Hợi", day: "Mậu Tý", hour: "Quý Hợi" },
      menh: "Tý",
      than: "Tuất",
      cuc: "Thổ ngũ cục",
      banMenh: "Bạch Lạp Kim",
      menhChu: "Vũ Khúc",
      thanChu: "Thiên Cơ",
      laiNhan: "Phụ Mẫu",
      menhCucRelation: "Cục Thổ sinh Mệnh Kim",
      firstDaiVan: { palace: "Mệnh", branch: "Tý", range: "5-14" },
      boneWeightLabel: "3 lượng 8 chỉ",
      mainStarsByPalace: {
        "Mệnh": ["Tử Vi"],
        "Phụ Mẫu": ["Vô chính diệu"],
        "Phúc Đức": ["Phá Quân"],
        "Điền Trạch": ["Vô chính diệu"],
        "Quan Lộc": ["Liêm Trinh", "Thiên Phủ"],
        "Nô Bộc": ["Thái Âm"],
        "Thiên Di": ["Tham Lang"],
        "Tật Ách": ["Thiên Đồng", "Cự Môn"],
        "Tài Bạch": ["Vũ Khúc", "Thiên Tướng"],
        "Tử Tức": ["Thái Dương", "Thiên Lương"],
        "Phu Thê": ["Thất Sát"],
        "Huynh Đệ": ["Thiên Cơ"],
      },
      supportStarsInclude: {
        "Mệnh": ["Địa Không", "Văn Tinh"],
        "Điền Trạch": ["Văn Khúc", "Hóa Khoa (Văn Khúc)"],
        "Quan Lộc": ["Linh Tinh", "Triệt"],
        "Nô Bộc": ["Triệt"],
        "Thiên Di": ["Thiên Không", "Đào Hoa"],
        "Tật Ách": ["Hóa Lộc (Cự Môn)"],
        "Tài Bạch": ["Đà La", "Tuần"],
        "Tử Tức": ["Hỏa Tinh", "Tuần", "Hóa Quyền (Thái Dương)"],
        "Phu Thê": ["Kình Dương", "Địa Kiếp"],
        "Huynh Đệ": ["Văn Xương", "Thiên Mã", "Hóa Kỵ (Văn Xương)"],
      },
      yearlyStarsInclude: {
        "Mệnh": ["L.Thiên Hư", "L.Thiên Khốc"],
        "Phúc Đức": ["L.Bạch Hổ"],
        "Quan Lộc": ["L.Đà La"],
        "Nô Bộc": ["L.Lộc Tồn"],
        "Thiên Di": ["LN Văn tinh", "L.Thái Tuế", "L.Kình Dương"],
        "Tài Bạch": ["L.Tang Môn", "L.Thiên Mã"],
      },
      starStatesInclude: {
        "Mệnh": { "Tử Vi": "Đ", "Địa Không": "H" },
        "Phúc Đức": { "Phá Quân": "H" },
        "Điền Trạch": { "Văn Khúc": "Đ", "Hóa Khoa (Văn Khúc)": "Đ" },
        "Quan Lộc": { "Liêm Trinh": "V", "Thiên Phủ": "V", "Linh Tinh": "Đ" },
        "Nô Bộc": { "Thái Âm": "H" },
        "Thiên Di": { "Tham Lang": "H" },
        "Tật Ách": { "Thiên Đồng": "H", "Cự Môn": "H", "Hóa Lộc (Cự Môn)": "Đ" },
        "Tài Bạch": { "Vũ Khúc": "V", "Thiên Tướng": "M", "Đà La": "Đ" },
        "Tử Tức": { "Thái Dương": "H", "Thiên Lương": "H", "Hỏa Tinh": "H", "Hóa Quyền (Thái Dương)": "Đ" },
        "Phu Thê": { "Thất Sát": "H", "Kình Dương": "Đ", "Địa Kiếp": "H", "Thiên Riêu": "H" },
        "Huynh Đệ": { "Thiên Cơ": "H", "Văn Xương": "Đ", "Thiên Mã": "Đ", "Hóa Kỵ (Văn Xương)": "H" },
      },
    },
  },
];

export function chartFixtureExternalValidationGaps(fixtures: ChartFixture[] = CHART_FIXTURES) {
  const externallyValidatedHours = new Set(
    fixtures
      .filter((fixture) => (EXTERNAL_FIXTURE_PROVENANCE as readonly string[]).includes(fixture.provenance))
      .map((fixture) => fixture.coverage.hourBranch),
  );

  return REQUIRED_GOLDEN_FIXTURE_HOURS.filter((hourBranch) => !externallyValidatedHours.has(hourBranch));
}
