import { mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { describe, expect, it, vi } from "vitest";
import { GET } from "./[filename]/route";

vi.mock("server-only", () => ({}));

describe("article upload route", () => {
  it("serves CMS-uploaded article images from the runtime upload directory", async () => {
    const filename = "cms-upload-00000000-0000-4000-8000-000000000000.webp";
    const filePath = path.join(process.cwd(), "public", "uploads", "articles", filename);
    await mkdir(path.dirname(filePath), { recursive: true });
    await writeFile(filePath, new Uint8Array([0x52, 0x49, 0x46, 0x46, 0x10, 0x00, 0x00, 0x00, 0x57, 0x45, 0x42, 0x50]));

    try {
      const response = await GET(new Request(`http://local.test/uploads/articles/${filename}`), { params: Promise.resolve({ filename }) });

      expect(response.status).toBe(200);
      expect(response.headers.get("Content-Type")).toBe("image/webp");
      expect(response.headers.get("X-Content-Type-Options")).toBe("nosniff");
      expect(new Uint8Array(await response.arrayBuffer()).slice(0, 4)).toEqual(new Uint8Array([0x52, 0x49, 0x46, 0x46]));
    } finally {
      await rm(filePath, { force: true });
    }
  });

  it("rejects upload filenames that were not generated by the CMS", async () => {
    const response = await GET(new Request("http://local.test/uploads/articles/../secret.env"), { params: Promise.resolve({ filename: "../secret.env" }) });

    expect(response.status).toBe(404);
  });
});
